[package]
name = "candymachinex"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/deps/move-stdlib/", rev = "devnet" }

[addresses]
std="0x1"
candymachinex =  "0x0"
sui =  "0000000000000000000000000000000000000002"
